#motor_1: left hand shouler lift(moving hand towards or away from body)
#motor_2: left hand roll in vertical plane 
#motor_3: left hand yaw about axix through the hand
#motor_4: left hand elbow joint lift
#motor_5: right hand shouler lift(moving hand towards or away from body)
#motor_6: right hand roll in vertical plane 
#motor_7: right hand yaw about axix through the hand
#motor_8: right hand elbow joint lift
motor_1:
  ID: 109
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_2:
  ID: 106
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_3:
  ID: 108
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_4:
  ID: 107
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_5:
  ID: 102
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_6:
  ID: 103
  Return_Delay_Time: 0
  Operating_Mode: 4
  
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_7:
  ID: 104
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
motor_8:
  ID: 105
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  PWM_Limit: 885
